version: "3"

services: 
  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: "amogus"
      POSTGRES_DB: IMDB
    volumes: 
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  admin:
    image: dpage/pgadmin4
    volumes: 
      - ./pgadmin:/var/lib/pgadmin
    ports: 
      - 8080:80
    environment: 
      PGADMIN_DEFAULT_EMAIL: "a@a.xyz"
      PGADMIN_DEFAULT_PASSWORD: amogus